import { createAccount, createClient } from "genlayer-js";
import { studioDevnet } from "genlayer-js/chains";
const contract=process.env.CONTRACT_ADDRESS?.trim(),raw=process.env.GENLAYER_PRIVATE_KEY?.trim(),sourceA=process.env.SOURCE_A?.trim(),sourceB=process.env.SOURCE_B?.trim(),sourceC=process.env.SOURCE_C?.trim();
if(!contract||!raw||!sourceA||!sourceB||!sourceC)throw new Error("CONTRACT_ADDRESS, GENLAYER_PRIVATE_KEY, SOURCE_A, SOURCE_B, and SOURCE_C are required");
const keeper=setInterval(()=>{},60000),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));const key=raw.startsWith("0x")?raw:`0x${raw}`;
const chain={...studioDevnet,id:61997,name:"GenLayer Studio Next",rpcUrls:{default:{http:["https://studio-next.genlayer.com/api"]}}};const client=createClient({chain,account:createAccount(key)});const incidentId=`weave-demo-${Date.now().toString(36)}`;console.log(`DEMO_INCIDENT=${incidentId}`);
async function finalized(hash){for(let attempt=0;attempt<300;attempt++){const receipt=await client.getTransaction({hash}).catch(()=>null);const status=String(receipt?.statusName??receipt?.status??"PENDING").toUpperCase();if(status==="FINALIZED")return receipt;if(["UNDETERMINED","DECLINED","CANCELED","CANCELLED"].includes(status))throw new Error(`Transaction ended ${status}`);await sleep(3000)}throw new Error("Transaction timed out before FINALIZED")}
async function write(label,functionName,args,intelligent=false){const fees=await client.estimateTransactionFees({leaderTimeunitsAllocation:intelligent?500n:180n,validatorTimeunitsAllocation:intelligent?600n:360n});const hash=await client.writeContract({address:contract,functionName,args,fees});console.log(`${label}_TX=${hash}`);const receipt=await finalized(hash);const status=String(receipt.statusName??receipt.status??"unknown"),execution=String(receipt.txExecutionResultName??receipt.txExecutionResult??"unknown"),consensus=String(receipt.resultName??receipt.result_name??"unknown");console.log(`${label}_STATUS=${status};EXECUTION_RESULT=${execution};CONSENSUS=${consensus}`);if(status!=="FINALIZED"||execution!=="FINISHED_WITH_RETURN"||consensus==="MAJORITY_DISAGREE")throw new Error(`${label} failed`);return hash}
const initialEvents=[{index:0,kind:"OUTAGE",source_index:0,time_quote:"09:45 UTC",quote:"Requests are failing for customers in Europe."},{index:1,kind:"OPERATIONAL",source_index:1,time_quote:"09:45 UTC",quote:"API traffic is operating normally in every region."}];
const conflict=[{left_event:0,right_event:1,reason:"Both sources describe the same checkpoint but disagree on whether the API is impaired."}];
await write("OPEN","open_incident",[incidentId,"Meridian API split report","Reconstruct the operational sequence and expose disagreements between public status reports before the postmortem is sealed.","October 3, 2026 from 09:00 to 11:00 UTC",JSON.stringify([sourceA,sourceB]),JSON.stringify(initialEvents),JSON.stringify(conflict)]);
await write("SYNTHESIZE_INITIAL","synthesize",[incidentId],true);const initial=await client.readContract({address:contract,functionName:"get_incident",args:[incidentId],jsonSafeReturn:true});console.log(`INITIAL_STATE=${JSON.stringify(initial)}`);if(initial.status!=="SYNTHESIZED"||!initial.weave?.conflicts?.length||initial.weave?.source_receipts?.length!==2)throw new Error("Initial weave did not preserve the source conflict");
const witnessEvent={kind:"RESOLVED",time_quote:"10:20 UTC",quote:"Error rates returned to normal and the incident is resolved."};
await write("ADD_WITNESS","add_witness_source",[incidentId,sourceC,JSON.stringify(witnessEvent),JSON.stringify(conflict)]);await write("SYNTHESIZE_WITNESS","synthesize",[incidentId],true);await write("SEAL","seal",[incidentId]);const finalState=await client.readContract({address:contract,functionName:"get_incident",args:[incidentId],jsonSafeReturn:true});console.log(`FINAL_STATE=${JSON.stringify(finalState)}`);if(finalState.status!=="SEALED"||finalState.revision!==1||finalState.weave?.source_receipts?.length!==3)throw new Error("Final live state is incorrect");clearInterval(keeper);
